services:
  fastapi-app:
    build: .
    restart: always
    container_name: palai
    image: palai
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:8000
    deploy:
      resources:
        reservations:
            cpus: '4.0'
            memory: 5000M
    command: ["gunicorn", "--preload", "--timeout", "60", "--workers", "16", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000", "server:api"]
